# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables:
- group: firebase-variables
trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install packages'

- script: |
    npm install -g @nrwl/cli
    npm install -g azure-functions-core-tools
  displayName: 'Nx & azure-functions-core-tools installation'

- script: |
    nx build api
  displayName: 'nx build api project'

- script: |
    func azure functionapp publish backend-challenge --nozip
  displayName: 'publish to azure'

